/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ViewShareIdRouteImport } from './routes/view.$shareId'
import { Route as AdminDocumentIdRouteImport } from './routes/admin/$documentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewShareIdRoute = ViewShareIdRouteImport.update({
  id: '/view/$shareId',
  path: '/view/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDocumentIdRoute = AdminDocumentIdRouteImport.update({
  id: '/admin/$documentId',
  path: '/admin/$documentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/$documentId': typeof AdminDocumentIdRoute
  '/view/$shareId': typeof ViewShareIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/$documentId': typeof AdminDocumentIdRoute
  '/view/$shareId': typeof ViewShareIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/$documentId': typeof AdminDocumentIdRoute
  '/view/$shareId': typeof ViewShareIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin/$documentId' | '/view/$shareId' | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin/$documentId' | '/view/$shareId' | '/admin'
  id: '__root__' | '/' | '/admin/$documentId' | '/view/$shareId' | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminDocumentIdRoute: typeof AdminDocumentIdRoute
  ViewShareIdRoute: typeof ViewShareIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view/$shareId': {
      id: '/view/$shareId'
      path: '/view/$shareId'
      fullPath: '/view/$shareId'
      preLoaderRoute: typeof ViewShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$documentId': {
      id: '/admin/$documentId'
      path: '/admin/$documentId'
      fullPath: '/admin/$documentId'
      preLoaderRoute: typeof AdminDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminDocumentIdRoute: AdminDocumentIdRoute,
  ViewShareIdRoute: ViewShareIdRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
